version: '3'
services:
    db:
        image: couchdb
        environment:
            - COUCHDB_USER=userx
            - COUCHDB_PASSWORD=passwordx
    web:
        build: .
        environment:
            - USER=userx
            - PASSWORD=passwordx
            - HOST=db
        command: node index.js
        ports:
            - '8000:8000'
        depends_on: 
            - db
